version: '2'
services:
    node:
        image: node
        volumes:
             - ./:/opt/techtree
        command: '/opt/techtree/start.sh'
        ports:
            - 80:8000
        links:
            - mysql:homestead
        env_file:
            - ./.mysql.env
    mysql:
        image: mariadb:latest
        env_file:
            - ./.mysql.env
        volumes:
            - ./storage/mysql:/var/lib/mysql